version: '3.8'

services:
  weatherapi:
    build: .
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Data Source=/data/weather.db
    volumes:
      - sqlite_data:/data

volumes:
  sqlite_data: